# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from shared.proto import avos_pb2 as shared_dot_proto_dot_avos__pb2

GRPC_GENERATED_VERSION = '1.81.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in shared/proto/avos_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class AvosServiceStub:
    """─── Services ─────────────────────────────────────────────────────────────────

    Main service: UI <-> CSO
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.StreamThreatEvents = channel.unary_stream(
                '/avos.AvosService/StreamThreatEvents',
                request_serializer=shared_dot_proto_dot_avos__pb2.GenericResponse.SerializeToString,
                response_deserializer=shared_dot_proto_dot_avos__pb2.ThreatEventProto.FromString,
                _registered_method=True)
        self.GetSystemStatus = channel.unary_unary(
                '/avos.AvosService/GetSystemStatus',
                request_serializer=shared_dot_proto_dot_avos__pb2.GenericResponse.SerializeToString,
                response_deserializer=shared_dot_proto_dot_avos__pb2.SystemStatus.FromString,
                _registered_method=True)
        self.SetModuleConfig = channel.unary_unary(
                '/avos.AvosService/SetModuleConfig',
                request_serializer=shared_dot_proto_dot_avos__pb2.ModuleConfigRequest.SerializeToString,
                response_deserializer=shared_dot_proto_dot_avos__pb2.GenericResponse.FromString,
                _registered_method=True)
        self.SetMode = channel.unary_unary(
                '/avos.AvosService/SetMode',
                request_serializer=shared_dot_proto_dot_avos__pb2.ModeRequest.SerializeToString,
                response_deserializer=shared_dot_proto_dot_avos__pb2.GenericResponse.FromString,
                _registered_method=True)
        self.GetThreats = channel.unary_unary(
                '/avos.AvosService/GetThreats',
                request_serializer=shared_dot_proto_dot_avos__pb2.ThreatListRequest.SerializeToString,
                response_deserializer=shared_dot_proto_dot_avos__pb2.ThreatListResponse.FromString,
                _registered_method=True)
        self.QuarantineFile = channel.unary_unary(
                '/avos.AvosService/QuarantineFile',
                request_serializer=shared_dot_proto_dot_avos__pb2.QuarantineRequest.SerializeToString,
                response_deserializer=shared_dot_proto_dot_avos__pb2.GenericResponse.FromString,
                _registered_method=True)
        self.ScanFile = channel.unary_unary(
                '/avos.AvosService/ScanFile',
                request_serializer=shared_dot_proto_dot_avos__pb2.ScanRequest.SerializeToString,
                response_deserializer=shared_dot_proto_dot_avos__pb2.ScanResponse.FromString,
                _registered_method=True)
        self.Chat = channel.unary_unary(
                '/avos.AvosService/Chat',
                request_serializer=shared_dot_proto_dot_avos__pb2.ChatRequest.SerializeToString,
                response_deserializer=shared_dot_proto_dot_avos__pb2.ChatResponse.FromString,
                _registered_method=True)
        self.GetBreachAlerts = channel.unary_unary(
                '/avos.AvosService/GetBreachAlerts',
                request_serializer=shared_dot_proto_dot_avos__pb2.GenericResponse.SerializeToString,
                response_deserializer=shared_dot_proto_dot_avos__pb2.BreachListResponse.FromString,
                _registered_method=True)
        self.LaunchSecureBrowser = channel.unary_unary(
                '/avos.AvosService/LaunchSecureBrowser',
                request_serializer=shared_dot_proto_dot_avos__pb2.BrowserLaunchRequest.SerializeToString,
                response_deserializer=shared_dot_proto_dot_avos__pb2.GenericResponse.FromString,
                _registered_method=True)
        self.TokenizeCardData = channel.unary_unary(
                '/avos.AvosService/TokenizeCardData',
                request_serializer=shared_dot_proto_dot_avos__pb2.TokenizeRequest.SerializeToString,
                response_deserializer=shared_dot_proto_dot_avos__pb2.TokenizeResponse.FromString,
                _registered_method=True)
        self.WipeClipboard = channel.unary_unary(
                '/avos.AvosService/WipeClipboard',
                request_serializer=shared_dot_proto_dot_avos__pb2.GenericResponse.SerializeToString,
                response_deserializer=shared_dot_proto_dot_avos__pb2.GenericResponse.FromString,
                _registered_method=True)
        self.AuditDns = channel.unary_unary(
                '/avos.AvosService/AuditDns',
                request_serializer=shared_dot_proto_dot_avos__pb2.DnsAuditRequest.SerializeToString,
                response_deserializer=shared_dot_proto_dot_avos__pb2.DnsAuditResponse.FromString,
                _registered_method=True)
        self.ScanRegistry = channel.unary_unary(
                '/avos.AvosService/ScanRegistry',
                request_serializer=shared_dot_proto_dot_avos__pb2.GenericResponse.SerializeToString,
                response_deserializer=shared_dot_proto_dot_avos__pb2.UtilityResponse.FromString,
                _registered_method=True)
        self.CleanTemp = channel.unary_unary(
                '/avos.AvosService/CleanTemp',
                request_serializer=shared_dot_proto_dot_avos__pb2.UtilityRequest.SerializeToString,
                response_deserializer=shared_dot_proto_dot_avos__pb2.UtilityResponse.FromString,
                _registered_method=True)
        self.LockFolder = channel.unary_unary(
                '/avos.AvosService/LockFolder',
                request_serializer=shared_dot_proto_dot_avos__pb2.UtilityRequest.SerializeToString,
                response_deserializer=shared_dot_proto_dot_avos__pb2.GenericResponse.FromString,
                _registered_method=True)
        self.UnlockFolder = channel.unary_unary(
                '/avos.AvosService/UnlockFolder',
                request_serializer=shared_dot_proto_dot_avos__pb2.UtilityRequest.SerializeToString,
                response_deserializer=shared_dot_proto_dot_avos__pb2.GenericResponse.FromString,
                _registered_method=True)
        self.GetFirewallRules = channel.unary_unary(
                '/avos.AvosService/GetFirewallRules',
                request_serializer=shared_dot_proto_dot_avos__pb2.GenericResponse.SerializeToString,
                response_deserializer=shared_dot_proto_dot_avos__pb2.FirewallRulesResponse.FromString,
                _registered_method=True)
        self.GetEDREvents = channel.unary_unary(
                '/avos.AvosService/GetEDREvents',
                request_serializer=shared_dot_proto_dot_avos__pb2.ThreatListRequest.SerializeToString,
                response_deserializer=shared_dot_proto_dot_avos__pb2.EDREventsResponse.FromString,
                _registered_method=True)


class AvosServiceServicer:
    """─── Services ─────────────────────────────────────────────────────────────────

    Main service: UI <-> CSO
    """

    def StreamThreatEvents(self, request, context):
        """Streaming threat events (UI subscribes to real-time alerts)
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetSystemStatus(self, request, context):
        """System status (dashboard)
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def SetModuleConfig(self, request, context):
        """Module management
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def SetMode(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetThreats(self, request, context):
        """Threat management
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def QuarantineFile(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ScanFile(self, request, context):
        """On-demand scanning
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Chat(self, request, context):
        """AI chatbot (offline, DB-context-aware)
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetBreachAlerts(self, request, context):
        """Dark web / breach alerts
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def LaunchSecureBrowser(self, request, context):
        """Payment Shield Actions
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def TokenizeCardData(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def WipeClipboard(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def AuditDns(self, request, context):
        """DNS Audit (real Cloudflare DoH check)
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ScanRegistry(self, request, context):
        """Utilities
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def CleanTemp(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def LockFolder(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def UnlockFolder(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetFirewallRules(self, request, context):
        """Firewall rules (real Windows Firewall via netsh)
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetEDREvents(self, request, context):
        """EDR events log
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_AvosServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'StreamThreatEvents': grpc.unary_stream_rpc_method_handler(
                    servicer.StreamThreatEvents,
                    request_deserializer=shared_dot_proto_dot_avos__pb2.GenericResponse.FromString,
                    response_serializer=shared_dot_proto_dot_avos__pb2.ThreatEventProto.SerializeToString,
            ),
            'GetSystemStatus': grpc.unary_unary_rpc_method_handler(
                    servicer.GetSystemStatus,
                    request_deserializer=shared_dot_proto_dot_avos__pb2.GenericResponse.FromString,
                    response_serializer=shared_dot_proto_dot_avos__pb2.SystemStatus.SerializeToString,
            ),
            'SetModuleConfig': grpc.unary_unary_rpc_method_handler(
                    servicer.SetModuleConfig,
                    request_deserializer=shared_dot_proto_dot_avos__pb2.ModuleConfigRequest.FromString,
                    response_serializer=shared_dot_proto_dot_avos__pb2.GenericResponse.SerializeToString,
            ),
            'SetMode': grpc.unary_unary_rpc_method_handler(
                    servicer.SetMode,
                    request_deserializer=shared_dot_proto_dot_avos__pb2.ModeRequest.FromString,
                    response_serializer=shared_dot_proto_dot_avos__pb2.GenericResponse.SerializeToString,
            ),
            'GetThreats': grpc.unary_unary_rpc_method_handler(
                    servicer.GetThreats,
                    request_deserializer=shared_dot_proto_dot_avos__pb2.ThreatListRequest.FromString,
                    response_serializer=shared_dot_proto_dot_avos__pb2.ThreatListResponse.SerializeToString,
            ),
            'QuarantineFile': grpc.unary_unary_rpc_method_handler(
                    servicer.QuarantineFile,
                    request_deserializer=shared_dot_proto_dot_avos__pb2.QuarantineRequest.FromString,
                    response_serializer=shared_dot_proto_dot_avos__pb2.GenericResponse.SerializeToString,
            ),
            'ScanFile': grpc.unary_unary_rpc_method_handler(
                    servicer.ScanFile,
                    request_deserializer=shared_dot_proto_dot_avos__pb2.ScanRequest.FromString,
                    response_serializer=shared_dot_proto_dot_avos__pb2.ScanResponse.SerializeToString,
            ),
            'Chat': grpc.unary_unary_rpc_method_handler(
                    servicer.Chat,
                    request_deserializer=shared_dot_proto_dot_avos__pb2.ChatRequest.FromString,
                    response_serializer=shared_dot_proto_dot_avos__pb2.ChatResponse.SerializeToString,
            ),
            'GetBreachAlerts': grpc.unary_unary_rpc_method_handler(
                    servicer.GetBreachAlerts,
                    request_deserializer=shared_dot_proto_dot_avos__pb2.GenericResponse.FromString,
                    response_serializer=shared_dot_proto_dot_avos__pb2.BreachListResponse.SerializeToString,
            ),
            'LaunchSecureBrowser': grpc.unary_unary_rpc_method_handler(
                    servicer.LaunchSecureBrowser,
                    request_deserializer=shared_dot_proto_dot_avos__pb2.BrowserLaunchRequest.FromString,
                    response_serializer=shared_dot_proto_dot_avos__pb2.GenericResponse.SerializeToString,
            ),
            'TokenizeCardData': grpc.unary_unary_rpc_method_handler(
                    servicer.TokenizeCardData,
                    request_deserializer=shared_dot_proto_dot_avos__pb2.TokenizeRequest.FromString,
                    response_serializer=shared_dot_proto_dot_avos__pb2.TokenizeResponse.SerializeToString,
            ),
            'WipeClipboard': grpc.unary_unary_rpc_method_handler(
                    servicer.WipeClipboard,
                    request_deserializer=shared_dot_proto_dot_avos__pb2.GenericResponse.FromString,
                    response_serializer=shared_dot_proto_dot_avos__pb2.GenericResponse.SerializeToString,
            ),
            'AuditDns': grpc.unary_unary_rpc_method_handler(
                    servicer.AuditDns,
                    request_deserializer=shared_dot_proto_dot_avos__pb2.DnsAuditRequest.FromString,
                    response_serializer=shared_dot_proto_dot_avos__pb2.DnsAuditResponse.SerializeToString,
            ),
            'ScanRegistry': grpc.unary_unary_rpc_method_handler(
                    servicer.ScanRegistry,
                    request_deserializer=shared_dot_proto_dot_avos__pb2.GenericResponse.FromString,
                    response_serializer=shared_dot_proto_dot_avos__pb2.UtilityResponse.SerializeToString,
            ),
            'CleanTemp': grpc.unary_unary_rpc_method_handler(
                    servicer.CleanTemp,
                    request_deserializer=shared_dot_proto_dot_avos__pb2.UtilityRequest.FromString,
                    response_serializer=shared_dot_proto_dot_avos__pb2.UtilityResponse.SerializeToString,
            ),
            'LockFolder': grpc.unary_unary_rpc_method_handler(
                    servicer.LockFolder,
                    request_deserializer=shared_dot_proto_dot_avos__pb2.UtilityRequest.FromString,
                    response_serializer=shared_dot_proto_dot_avos__pb2.GenericResponse.SerializeToString,
            ),
            'UnlockFolder': grpc.unary_unary_rpc_method_handler(
                    servicer.UnlockFolder,
                    request_deserializer=shared_dot_proto_dot_avos__pb2.UtilityRequest.FromString,
                    response_serializer=shared_dot_proto_dot_avos__pb2.GenericResponse.SerializeToString,
            ),
            'GetFirewallRules': grpc.unary_unary_rpc_method_handler(
                    servicer.GetFirewallRules,
                    request_deserializer=shared_dot_proto_dot_avos__pb2.GenericResponse.FromString,
                    response_serializer=shared_dot_proto_dot_avos__pb2.FirewallRulesResponse.SerializeToString,
            ),
            'GetEDREvents': grpc.unary_unary_rpc_method_handler(
                    servicer.GetEDREvents,
                    request_deserializer=shared_dot_proto_dot_avos__pb2.ThreatListRequest.FromString,
                    response_serializer=shared_dot_proto_dot_avos__pb2.EDREventsResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'avos.AvosService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('avos.AvosService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class AvosService:
    """─── Services ─────────────────────────────────────────────────────────────────

    Main service: UI <-> CSO
    """

    @staticmethod
    def StreamThreatEvents(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(
            request,
            target,
            '/avos.AvosService/StreamThreatEvents',
            shared_dot_proto_dot_avos__pb2.GenericResponse.SerializeToString,
            shared_dot_proto_dot_avos__pb2.ThreatEventProto.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetSystemStatus(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/avos.AvosService/GetSystemStatus',
            shared_dot_proto_dot_avos__pb2.GenericResponse.SerializeToString,
            shared_dot_proto_dot_avos__pb2.SystemStatus.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def SetModuleConfig(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/avos.AvosService/SetModuleConfig',
            shared_dot_proto_dot_avos__pb2.ModuleConfigRequest.SerializeToString,
            shared_dot_proto_dot_avos__pb2.GenericResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def SetMode(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/avos.AvosService/SetMode',
            shared_dot_proto_dot_avos__pb2.ModeRequest.SerializeToString,
            shared_dot_proto_dot_avos__pb2.GenericResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetThreats(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/avos.AvosService/GetThreats',
            shared_dot_proto_dot_avos__pb2.ThreatListRequest.SerializeToString,
            shared_dot_proto_dot_avos__pb2.ThreatListResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def QuarantineFile(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/avos.AvosService/QuarantineFile',
            shared_dot_proto_dot_avos__pb2.QuarantineRequest.SerializeToString,
            shared_dot_proto_dot_avos__pb2.GenericResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ScanFile(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/avos.AvosService/ScanFile',
            shared_dot_proto_dot_avos__pb2.ScanRequest.SerializeToString,
            shared_dot_proto_dot_avos__pb2.ScanResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Chat(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/avos.AvosService/Chat',
            shared_dot_proto_dot_avos__pb2.ChatRequest.SerializeToString,
            shared_dot_proto_dot_avos__pb2.ChatResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetBreachAlerts(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/avos.AvosService/GetBreachAlerts',
            shared_dot_proto_dot_avos__pb2.GenericResponse.SerializeToString,
            shared_dot_proto_dot_avos__pb2.BreachListResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def LaunchSecureBrowser(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/avos.AvosService/LaunchSecureBrowser',
            shared_dot_proto_dot_avos__pb2.BrowserLaunchRequest.SerializeToString,
            shared_dot_proto_dot_avos__pb2.GenericResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def TokenizeCardData(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/avos.AvosService/TokenizeCardData',
            shared_dot_proto_dot_avos__pb2.TokenizeRequest.SerializeToString,
            shared_dot_proto_dot_avos__pb2.TokenizeResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def WipeClipboard(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/avos.AvosService/WipeClipboard',
            shared_dot_proto_dot_avos__pb2.GenericResponse.SerializeToString,
            shared_dot_proto_dot_avos__pb2.GenericResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def AuditDns(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/avos.AvosService/AuditDns',
            shared_dot_proto_dot_avos__pb2.DnsAuditRequest.SerializeToString,
            shared_dot_proto_dot_avos__pb2.DnsAuditResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ScanRegistry(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/avos.AvosService/ScanRegistry',
            shared_dot_proto_dot_avos__pb2.GenericResponse.SerializeToString,
            shared_dot_proto_dot_avos__pb2.UtilityResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def CleanTemp(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/avos.AvosService/CleanTemp',
            shared_dot_proto_dot_avos__pb2.UtilityRequest.SerializeToString,
            shared_dot_proto_dot_avos__pb2.UtilityResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def LockFolder(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/avos.AvosService/LockFolder',
            shared_dot_proto_dot_avos__pb2.UtilityRequest.SerializeToString,
            shared_dot_proto_dot_avos__pb2.GenericResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def UnlockFolder(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/avos.AvosService/UnlockFolder',
            shared_dot_proto_dot_avos__pb2.UtilityRequest.SerializeToString,
            shared_dot_proto_dot_avos__pb2.GenericResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetFirewallRules(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/avos.AvosService/GetFirewallRules',
            shared_dot_proto_dot_avos__pb2.GenericResponse.SerializeToString,
            shared_dot_proto_dot_avos__pb2.FirewallRulesResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetEDREvents(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/avos.AvosService/GetEDREvents',
            shared_dot_proto_dot_avos__pb2.ThreatListRequest.SerializeToString,
            shared_dot_proto_dot_avos__pb2.EDREventsResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
